services:
  pipman-web:
    image: beesar/analytics-pipeline:latest
    profiles: ["analytics", "all", "pipeline", "pipman"]
    container_name: nayarta-nai-pipman-web
    restart: unless-stopped
    ports:
      - "4080:8000"
    environment:
      # Debug Mode
      - DEBUG=${DEBUG:-True}

      # ========= NAYARTA =========
      - NAYARTA_URL=${API_BASE_URL_ANALYTICS:-http://localhost:8457}
      - NAYARTA_STREAM_URL=${NAYARTA_STREAM_URL:-rtsp://localhost:8554/}
      - NAYARTA_API_KEY=${API_KEY_PIPELINE:-VRX986-90-BA-77654NY}
      - PIPMAN_URL=${PIPMAN_URL:-http://${HOST_IP:-localhost}:8000}

      # ========= CLICKHOUSE =========
      - ch_host=${CLICKHOUSE_HOST:-localhost}
      - ch_uname=${CLICKHOUSE_USER:-default}
      - ch_password=${CLICKHOUSE_PASSWORD:-beEs4rP@ssW0rD!}
      - ch_port=${CLICKHOUSE_PORT:-8124}
      - ch_dbname=${CLICKHOUSE_DB:-default}
      - ch_secure=${CLICKHOUSE_SECURE:-False}

      # ========= RABBITMQ =========
      - RMQ_USER=${RABBITMQ_USER:-queueuser}
      - RMQ_PASS=${RABBITMQ_PASSWORD:-queuePassword}
      - RMQ_HOST=${RABBITMQ_HOST:-nayarta-rabbitmq}
      - RMQ_PORT=${RABBITMQ_PORT:-5672}

      # ========= MQTT =========
      - MQTT_BROKER=${MQTT_BROKER:-nayarta-mqtt}
      - MQTT_PORT=${MQTT_PORT:-9000}
      - MQTT_TOPIC=${MQTT_TOPIC:-nayai/analytic_update}
      - MQTT_UNAME=${MQTT_USER:-mqttuser}
      - MQTT_PASS=${MQTT_PASSWORD:-mqttpassword}

      # ========= POSTGRES =========
      - PG_HOST=${DB_HOST_ANALYTICS:-nayarta-postgres}
      - PG_PORT=${DB_PORT_ANALYTICS:-5432}
      - PG_DB=${DB_NAME_ANALYTICS:-analytics_db}
      - PG_USER=${DB_USER_ANALYTICS:-admin}
      - PG_PASS=${DB_PASSWORD_ANALYTICS:-admin122}

      # ========= DIRECTORIES =========
      - RUNTIME_FOLDER=${RUNTIME_FOLDER:-/app/shared_folder}
      - LOG_FOLDER=${LOG_FOLDER:-/app/logs}
    working_dir: /app/pipman/pipmanweb
    command: >
        sh -c "
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
        "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - nayarta-network

  # Scheduler Application
  pipman:
    image: beesar/analytics-pipeline:latest
    profiles: ["analytics", "all", "pipeline", "pipman"]
    container_name: nayarta-nai-pipman
    restart: unless-stopped
    environment:
      # Debug Mode
      - DEBUG=${DEBUG:-True}

      # ========= PYTHON PATH =========
      - PYTHON_PATH=/usr/bin/python

      # ========= NAYARTA =========
      - NAYARTA_URL=${API_BASE_URL_ANALYTICS:-http://localhost:8457}
      - NAYARTA_STREAM_URL=${NAYARTA_STREAM_URL:-rtsp://localhost:8554/}
      - NAYARTA_API_KEY=${API_KEY_PIPELINE:-VRX986-90-BA-77654NY}
      - PIPMAN_URL=${PIPMAN_URL:-http://pipman-web:8000}

      # ========= CLICKHOUSE =========
      - ch_host=${CLICKHOUSE_HOST:-nayarta-ch-server}
      - ch_uname=${CLICKHOUSE_USER:-default}
      - ch_password=${CLICKHOUSE_PASSWORD:-beEs4rP@ssW0rD!}
      - ch_port=${CLICKHOUSE_PORT:-9000}
      - ch_dbname=${CLICKHOUSE_DB:-default}
      - ch_secure=${CLICKHOUSE_SECURE:-False}

      # ========= RABBITMQ =========
      - RMQ_USER=${RABBITMQ_USER:-queueuser}
      - RMQ_PASS=${RABBITMQ_PASSWORD:-queuePassword}
      - RMQ_HOST=${RABBITMQ_HOST:-nayarta-rabbitmq}
      - RMQ_PORT=${RABBITMQ_PORT:-5672}

      # ========= MQTT =========
      - MQTT_BROKER=${MQTT_BROKER:-nayarta-mqtt}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_TOPIC=${MQTT_TOPIC:-nayai/analytic_update}
      - MQTT_UNAME=${MQTT_USER:-mqttuser}
      - MQTT_PASS=${MQTT_PASSWORD:-mqttpassword}

      # ========= POSTGRES =========
      - PG_HOST=${DB_HOST_ANALYTICS:-nayarta-postgres}
      - PG_PORT=${DB_PORT_ANALYTICS:-5432}
      - PG_DB=${DB_NAME_ANALYTICS:-analytics_db}
      - PG_USER=${DB_USER_ANALYTICS:-admin}
      - PG_PASS=${DB_PASSWORD_ANALYTICS:-admin122}

      # ========= DIRECTORIES =========
      - RUNTIME_FOLDER=${RUNTIME_FOLDER:-/app/shared_folder}
      - LOG_FOLDER=${LOG_FOLDER:-/app/logs}
    working_dir: /app/pipman
    command: python pipman.py
    networks:
      - nayarta-network
    depends_on:
      - pipman-web
    volumes:
      - ${HOST_PROJECT_ROOT:-.}/analytics/pipeline/shared_folder:/shared_folder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "com.project.name=nayarta"
      - "com.project.profile=analytics"
      - "com.project.profile=pipeline"
      - "com.project.profile=pipman"

  task-service:
    image: beesar/analytics-pipeline:latest
    profiles: ["analytics", "all", "pipeline", "task"]
    container_name: nayarta-nai-task
    restart: unless-stopped
    environment:
      # Debug Mode
      - DEBUG=${DEBUG:-False}
      # ========= NAYARTA =========
      - NAYARTA_URL=${API_BASE_URL_ANALYTICS:-http://localhost:8457}
      - NAYARTA_STREAM_URL=${NAYARTA_STREAM_URL:-rtsp://localhost:8554/}
      - NAYARTA_API_KEY=${API_KEY_PIPELINE:-VRX986-90-BA-77654NY}
      - PIPMAN_URL=${PIPMAN_URL:-http://pipman-web:8000}

      # ========= CLICKHOUSE =========
      - ch_host=${CLICKHOUSE_HOST:-nayarta-ch-server}
      - ch_uname=${CLICKHOUSE_USER:-default}
      - ch_password=${CLICKHOUSE_PASSWORD:-beEs4rP@ssW0rD!}
      - ch_port=${CLICKHOUSE_PORT:-9000}
      - ch_dbname=${CLICKHOUSE_DB:-default}
      - ch_secure=${CLICKHOUSE_SECURE:-False}

      # ========= RABBITMQ =========
      - RMQ_USER=${RABBITMQ_USER:-queueuser}
      - RMQ_PASS=${RABBITMQ_PASSWORD:-queuePassword}
      - RMQ_HOST=${RABBITMQ_HOST:-nayarta-rabbitmq}
      - RMQ_PORT=${RABBITMQ_PORT:-5672}

      # ========= MQTT =========
      - MQTT_BROKER=${MQTT_BROKER:-nayarta-mqtt}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_TOPIC=${MQTT_TOPIC:-nayai/analytic_update}
      - MQTT_UNAME=${MQTT_USER:-mqttuser}
      - MQTT_PASS=${MQTT_PASSWORD:-mqttpassword}

      # ========= POSTGRES =========
      - PG_HOST=${DB_HOST_ANALYTICS:-nayarta-postgres}
      - PG_PORT=${DB_PORT_ANALYTICS:-5432}
      - PG_DB=${DB_NAME_ANALYTICS:-analytics_db}
      - PG_USER=${DB_USER_ANALYTICS:-admin}
      - PG_PASS=${DB_PASSWORD_ANALYTICS:-admin122}

      # ========= DIRECTORIES =========
      - RUNTIME_FOLDER=${RUNTIME_FOLDER:-/app/shared_folder}
      - LOG_FOLDER=${LOG_FOLDER:-/app/logs}

      # ========= YOLO =========
      - YOLO_CONFIG_DIR=/app/.ultralytics
    working_dir: /app/task
    command: celery -A tasks:app worker -l info --autoscale=50,1 -Q io,db,control -n subtasks@%h
    volumes:
      - ${HOST_PROJECT_ROOT:-.}/analytics/pipeline/shared_folder:/app/shared_folder
    networks:
      - nayarta-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "com.project.name=nayarta"
      - "com.project.profile=analytics"
      - "com.project.profile=pipeline"
      - "com.project.profile=task"

